if(NOT DEFINED SECUREKIT_WORKFLOW_FILE)
  set(SECUREKIT_WORKFLOW_FILE "${CMAKE_CURRENT_LIST_DIR}/../../.github/workflows/securekit-ci.yml")
endif()

if(NOT DEFINED SECUREKIT_CODEQL_WORKFLOW_FILE)
  set(SECUREKIT_CODEQL_WORKFLOW_FILE "${CMAKE_CURRENT_LIST_DIR}/../../.github/workflows/codeql.yml")
endif()

if(NOT EXISTS "${SECUREKIT_WORKFLOW_FILE}")
  message(FATAL_ERROR "Workflow file not found: ${SECUREKIT_WORKFLOW_FILE}")
endif()

if(NOT EXISTS "${SECUREKIT_CODEQL_WORKFLOW_FILE}")
  message(FATAL_ERROR "CodeQL workflow file not found: ${SECUREKIT_CODEQL_WORKFLOW_FILE}")
endif()

file(READ "${SECUREKIT_WORKFLOW_FILE}" _securekit_workflow)
file(READ "${SECUREKIT_CODEQL_WORKFLOW_FILE}" _securekit_codeql_workflow)

function(_securekit_require_workflow_text description needle)
  string(FIND "${_securekit_workflow}" "${needle}" _securekit_found_at)
  if(_securekit_found_at EQUAL -1)
    message(FATAL_ERROR "Workflow missing ${description}: ${needle}")
  endif()
endfunction()

function(_securekit_require_codeql_text description needle)
  string(FIND "${_securekit_codeql_workflow}" "${needle}" _securekit_found_at)
  if(_securekit_found_at EQUAL -1)
    message(FATAL_ERROR "CodeQL workflow missing ${description}: ${needle}")
  endif()
endfunction()

function(_securekit_require_codeql_regex description pattern)
  string(REGEX MATCH "${pattern}" _securekit_match "${_securekit_codeql_workflow}")
  if(_securekit_match STREQUAL "")
    message(FATAL_ERROR "CodeQL workflow missing ${description}: ${pattern}")
  endif()
endfunction()

_securekit_require_workflow_text("tag trigger" "tags:")
_securekit_require_workflow_text("v tag pattern" "- 'v*'")
_securekit_require_workflow_text("release job" "release:")
_securekit_require_workflow_text("release dependency on build matrix" "needs: [build, install-only, linux-static, windows-shared]")
_securekit_require_workflow_text("release tag guard" "startsWith(github.ref, 'refs/tags/v')")
_securekit_require_workflow_text("current checkout action" "uses: actions/checkout@v7")
_securekit_require_workflow_text("current cache action" "uses: actions/cache@v5")
_securekit_require_workflow_text("current upload artifact action" "uses: actions/upload-artifact@v7")
_securekit_require_workflow_text("release artifact download" "uses: actions/download-artifact@v8")
_securekit_require_workflow_text("release tag version extraction" "tag_version=\"\${GITHUB_REF_NAME#v}\"")
_securekit_require_workflow_text("release artifact version guard" "Release artifact version does not match tag")
_securekit_require_workflow_text("release SemVer tag guard" "Release tag is not SemVer")
_securekit_require_workflow_text("release binary artifact prefix" "dist/\${artifact_name}-\${base}")
_securekit_require_workflow_text("release source artifact de-duplication" "copied_source")
_securekit_require_workflow_text("release checksum generation" "sha256sum")
_securekit_require_workflow_text("release checksum file" "SHA256SUMS.txt")
_securekit_require_workflow_text("release creation" "gh release create")
_securekit_require_workflow_text("release asset upload" "gh release upload")

_securekit_require_codeql_text("workflow name" "name: \"CodeQL\"")
_securekit_require_codeql_regex("main push trigger" "push:[\r\n]+    branches: \\[ \"main\" \\]")
_securekit_require_codeql_regex("main pull request trigger" "pull_request:[\r\n]+    branches: \\[ \"main\" \\]")
_securekit_require_codeql_regex("scheduled analysis" "schedule:[\r\n]+    - cron:")
_securekit_require_codeql_text("current checkout action" "uses: actions/checkout@v7")
_securekit_require_codeql_text("current CodeQL init action" "uses: github/codeql-action/init@v4")
_securekit_require_codeql_text("manual CodeQL build mode" "build-mode: manual")
_securekit_require_codeql_text("manual CMake configure" "cmake -S . -B build-codeql")
_securekit_require_codeql_text("manual CMake build" "cmake --build build-codeql --config Release")
_securekit_require_codeql_text("current CodeQL analyze action" "uses: github/codeql-action/analyze@v4")
