if(NOT DEFINED SECUREKIT_CLI)
  message(FATAL_ERROR "SECUREKIT_CLI is required")
endif()

if(NOT DEFINED SECUREKIT_CLI_WORK_DIR)
  message(FATAL_ERROR "SECUREKIT_CLI_WORK_DIR is required")
endif()

if(NOT DEFINED SECUREKIT_TEST_FIXTURE_DIR)
  get_filename_component(_securekit_test_dir "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY)
  set(SECUREKIT_TEST_FIXTURE_DIR "${_securekit_test_dir}/fixtures")
endif()

if(NOT DEFINED SECUREKIT_EXPECTED_VERSION)
  get_filename_component(_securekit_cli_dir "${SECUREKIT_CLI}" DIRECTORY)
  get_filename_component(_securekit_install_prefix "${_securekit_cli_dir}" DIRECTORY)
  set(_securekit_version_file "${_securekit_install_prefix}/lib/cmake/securekit/securekitConfigVersion.cmake")
  if(NOT EXISTS "${_securekit_version_file}")
    message(FATAL_ERROR "SECUREKIT_EXPECTED_VERSION is required when installed package version file is unavailable")
  endif()
  file(READ "${_securekit_version_file}" _securekit_version_text)
  string(REGEX MATCH "set\\(PACKAGE_VERSION \"([0-9]+\\.[0-9]+\\.[0-9]+)\"\\)" _securekit_version_match "${_securekit_version_text}")
  if(NOT _securekit_version_match)
    message(FATAL_ERROR "Could not read package version from ${_securekit_version_file}")
  endif()
  set(SECUREKIT_EXPECTED_VERSION "${CMAKE_MATCH_1}")
endif()

function(run_cli expected_exit expected_stdout)
  execute_process(
    COMMAND "${SECUREKIT_CLI}" ${ARGN}
    RESULT_VARIABLE result
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr)

  if(NOT result EQUAL expected_exit)
    message(FATAL_ERROR "Expected exit ${expected_exit}, got ${result}. stderr=${stderr}")
  endif()
  if(NOT stdout STREQUAL expected_stdout)
    message(FATAL_ERROR "Unexpected stdout. Expected [${expected_stdout}], got [${stdout}]")
  endif()
  if(expected_exit EQUAL 0 AND NOT stderr STREQUAL "")
    message(FATAL_ERROR "Successful command should not write stderr. stderr=[${stderr}]")
  endif()
endfunction()

function(run_cli_no_stdout)
  execute_process(
    COMMAND "${SECUREKIT_CLI}" ${ARGN}
    RESULT_VARIABLE result
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr)

  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Expected command to pass, got ${result}. stderr=${stderr}")
  endif()
  if(NOT stdout STREQUAL "")
    message(FATAL_ERROR "Command should not write stdout. stdout=[${stdout}]")
  endif()
  if(NOT stderr STREQUAL "")
    message(FATAL_ERROR "Successful command should not write stderr. stderr=[${stderr}]")
  endif()
endfunction()

function(run_cli_pipe input_file output_file)
  execute_process(
    COMMAND "${SECUREKIT_CLI}" ${ARGN}
    INPUT_FILE "${input_file}"
    OUTPUT_FILE "${output_file}"
    RESULT_VARIABLE result
    ERROR_VARIABLE stderr)

  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Expected piped command to pass, got ${result}. stderr=${stderr}")
  endif()
  if(NOT stderr STREQUAL "")
    message(FATAL_ERROR "Piped command should not write stderr. stderr=[${stderr}]")
  endif()
endfunction()

function(run_cli_failure expected_stderr)
  execute_process(
    COMMAND "${SECUREKIT_CLI}" ${ARGN}
    RESULT_VARIABLE result
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr)

  if(result EQUAL 0)
    message(FATAL_ERROR "Expected command to fail: ${ARGN}")
  endif()
  if(NOT stdout STREQUAL "")
    message(FATAL_ERROR "Failed command should not write stdout. stdout=[${stdout}]")
  endif()
  if(NOT stderr STREQUAL expected_stderr)
    message(FATAL_ERROR "Unexpected stderr. Expected [${expected_stderr}], got [${stderr}]")
  endif()
endfunction()

function(read_hex_fixture output_variable name)
  set(path "${SECUREKIT_TEST_FIXTURE_DIR}/${name}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Missing fixture: ${path}")
  endif()
  file(READ "${path}" hex_text)
  string(REGEX REPLACE "[ \t\r\n]" "" hex_text "${hex_text}")
  set(${output_variable} "${hex_text}" PARENT_SCOPE)
endfunction()

file(MAKE_DIRECTORY "${SECUREKIT_CLI_WORK_DIR}")

set(expected_version "securekit ${SECUREKIT_EXPECTED_VERSION}\n")
set(expected_version_help "Usage:\n  securekit version\n  securekit --version\n")
set(expected_seal_file_help "Usage:\n  securekit seal-file --in <path|-> --out <path|-> (--key-hex <64-hex>|--key-file <path>) [--aad-text <text>|--aad-hex <hex>]\n")
set(expected_seal_file_password_help "Usage:\n  securekit seal-file-password --in <path|-> --out <path|-> --password-file <path> [--aad-text <text>|--aad-hex <hex>]\n")
set(expected_encrypt_help "Usage:\n  securekit encrypt (--text <text>|--in <path>) (--key-hex <64-hex>|--key-file <path>) [--aad-text <text>|--aad-hex <hex>] [--out <path>]\n")
run_cli(0 "${expected_version}" version)
run_cli(0 "${expected_version}" --version)
run_cli(0 "${expected_version_help}" help version)
run_cli(0 "${expected_seal_file_help}" help seal-file)
run_cli(0 "${expected_seal_file_password_help}" help seal-file-password)
run_cli(0 "${expected_encrypt_help}" help encrypt)
run_cli(0 "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad\n" sha256 --text abc)
run_cli(0 "5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843\n" hmac-sha256 --key-hex 4a656665 --text "what do ya want for nothing?")
run_cli(0 "3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865\n" hkdf-sha256 --key-hex 0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b --salt-hex 000102030405060708090a0b0c --info-hex f0f1f2f3f4f5f6f7f8f9 --out-size 42)
run_cli(0 "616263\n" hex-encode --text abc)
run_cli(0 "abc\n" hex-decode --text 616263)

set(key_to_wrap "101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f")
set(wrapping_key "404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f")
set(key_to_wrap_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-key-to-wrap.hex")
set(wrapping_key_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-wrapping-key.hex")
set(wrapped_key_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-wrapped-key.skt")
set(unwrapped_key_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-unwrapped-key.hex")
file(WRITE "${key_to_wrap_file}" "${key_to_wrap}\n")
file(WRITE "${wrapping_key_file}" "${wrapping_key}\n")
file(REMOVE "${wrapped_key_file}")
file(REMOVE "${unwrapped_key_file}")
execute_process(
  COMMAND "${SECUREKIT_CLI}" wrap-key --key-hex "${key_to_wrap}" --wrapping-key-hex "${wrapping_key}"
  RESULT_VARIABLE wrap_key_result
  OUTPUT_VARIABLE wrap_key_stdout
  ERROR_VARIABLE wrap_key_stderr)
if(NOT wrap_key_result EQUAL 0)
  message(FATAL_ERROR "wrap-key failed: ${wrap_key_stderr}")
endif()
string(STRIP "${wrap_key_stdout}" wrapped_key_packet)
string(LENGTH "${wrapped_key_packet}" wrapped_key_packet_length)
if(NOT wrapped_key_packet_length EQUAL 130 OR NOT wrapped_key_packet MATCHES "^534b543101[0-9a-f]+$")
  message(FATAL_ERROR "wrap-key did not write a hex SKT1 packet: [${wrap_key_stdout}]")
endif()
run_cli(0 "${key_to_wrap}\n" unwrap-key --packet-hex "${wrapped_key_packet}" --wrapping-key-hex "${wrapping_key}")
run_cli_no_stdout(wrap-key --key-file "${key_to_wrap_file}" --wrapping-key-file "${wrapping_key_file}" --out "${wrapped_key_file}")
file(READ "${wrapped_key_file}" wrapped_key_file_hex HEX)
string(LENGTH "${wrapped_key_file_hex}" wrapped_key_file_hex_length)
if(NOT wrapped_key_file_hex_length EQUAL 130 OR NOT wrapped_key_file_hex MATCHES "^534b543101[0-9a-f]+$")
  message(FATAL_ERROR "wrap-key --out did not write a binary SKT1 packet")
endif()
run_cli_no_stdout(unwrap-key --packet-file "${wrapped_key_file}" --wrapping-key-file "${wrapping_key_file}" --out "${unwrapped_key_file}")
file(READ "${unwrapped_key_file}" unwrapped_key_text)
if(NOT unwrapped_key_text STREQUAL "${key_to_wrap}\n")
  message(FATAL_ERROR "unwrap-key --out did not write a key-file compatible hex key. got=[${unwrapped_key_text}]")
endif()

execute_process(
  COMMAND "${SECUREKIT_CLI}" token 16
  RESULT_VARIABLE token_result
  OUTPUT_VARIABLE token_stdout
  ERROR_VARIABLE token_stderr)
if(NOT token_result EQUAL 0)
  message(FATAL_ERROR "token command failed: ${token_stderr}")
endif()
string(STRIP "${token_stdout}" token_text)
string(LENGTH "${token_text}" token_length)
if(NOT token_length EQUAL 22 OR token_text MATCHES "[^A-Za-z0-9_-]")
  message(FATAL_ERROR "token output is not 22-char unpadded Base64URL text: [${token_stdout}]")
endif()

set(plain_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-plain.txt")
set(key_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-key.hex")
set(sealed_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-plain.skf")
set(opened_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-opened.txt")
set(temp_collision_sealed_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-temp-collision.skf")
set(temp_collision_sealed_temp_file "${temp_collision_sealed_file}.securekit.tmp")
set(temp_collision_opened_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-temp-collision-opened.txt")
set(temp_collision_opened_temp_file "${temp_collision_opened_file}.securekit.tmp")
set(password_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-password.bin")
set(wrong_password_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-wrong-password.bin")
set(password_sealed_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-password.skp")
set(password_opened_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-password-opened.txt")
set(password_wrong_opened_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-password-wrong-opened.txt")
set(pipe_sealed_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-pipe.skf")
set(pipe_opened_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-pipe-opened.txt")
set(password_pipe_sealed_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-password-pipe.skp")
set(password_pipe_opened_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-password-pipe-opened.txt")
set(unwrapped_key_sealed_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-unwrapped-key.skf")
set(unwrapped_key_opened_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-unwrapped-key-opened.txt")
set(conflicting_key_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-conflict.skf")
set(packet_zero_key "0000000000000000000000000000000000000000000000000000000000000000")
read_hex_fixture(packet_known_aad "skt1-aes256-gcm-aad.hex")
set(packet_aad_hex "7265636f72643a7631")
set(packet_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-packet.skt")
set(packet_opened_file "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-packet-opened.txt")

file(WRITE "${plain_file}" "installed CLI plaintext\n")
file(WRITE "${password_file}" "installed password bytes\n")
file(WRITE "${wrong_password_file}" "wrong installed password bytes\n")
file(REMOVE "${key_file}")
file(REMOVE "${sealed_file}")
file(REMOVE "${opened_file}")
file(REMOVE "${temp_collision_sealed_file}")
file(REMOVE "${temp_collision_sealed_temp_file}")
file(REMOVE "${temp_collision_opened_file}")
file(REMOVE "${temp_collision_opened_temp_file}")
file(REMOVE "${password_sealed_file}")
file(REMOVE "${password_opened_file}")
file(REMOVE "${password_wrong_opened_file}")
file(REMOVE "${pipe_sealed_file}")
file(REMOVE "${pipe_opened_file}")
file(REMOVE "${password_pipe_sealed_file}")
file(REMOVE "${password_pipe_opened_file}")
file(REMOVE "${unwrapped_key_sealed_file}")
file(REMOVE "${unwrapped_key_opened_file}")
file(REMOVE "${conflicting_key_file}")
file(REMOVE "${packet_file}")
file(REMOVE "${packet_opened_file}")

run_cli_no_stdout(keygen --out "${key_file}")
file(READ "${key_file}" generated_key)
string(STRIP "${generated_key}" generated_key_text)
string(LENGTH "${generated_key_text}" generated_key_length)
if(NOT generated_key_length EQUAL 64 OR generated_key_text MATCHES "[^0-9a-f]")
  message(FATAL_ERROR "keygen output is not 64 lowercase hex characters: [${generated_key}]")
endif()

run_cli(0 "hello securekit\n" decrypt --packet-hex "${packet_known_aad}" --key-hex "${packet_zero_key}" --aad-text record:v1)
execute_process(
  COMMAND "${SECUREKIT_CLI}" encrypt --text "installed packet" --key-file "${key_file}" --aad-text record:v1
  RESULT_VARIABLE packet_encrypt_result
  OUTPUT_VARIABLE packet_encrypt_stdout
  ERROR_VARIABLE packet_encrypt_stderr)
if(NOT packet_encrypt_result EQUAL 0)
  message(FATAL_ERROR "installed CLI encrypt failed: ${packet_encrypt_stderr}")
endif()
string(STRIP "${packet_encrypt_stdout}" packet_stdout_hex)
string(LENGTH "${packet_stdout_hex}" packet_stdout_hex_length)
if(packet_stdout_hex_length LESS 66 OR NOT packet_stdout_hex MATCHES "^534b543101[0-9a-f]+$")
  message(FATAL_ERROR "installed CLI encrypt did not write a hex SKT1 packet: [${packet_encrypt_stdout}]")
endif()
run_cli(0 "installed packet\n" decrypt --packet-hex "${packet_stdout_hex}" --key-file "${key_file}" --aad-hex "${packet_aad_hex}")

run_cli_no_stdout(seal-file --out "${sealed_file}" --key-file "${key_file}" --aad-text record:v1 --in "${plain_file}")
run_cli_no_stdout(open-file --key-file "${key_file}" --out "${opened_file}" --aad-text record:v1 --in "${sealed_file}")
file(READ "${opened_file}" opened_text)
if(NOT opened_text STREQUAL "installed CLI plaintext\n")
  message(FATAL_ERROR "installed CLI open did not recover plaintext. got=[${opened_text}]")
endif()

file(WRITE "${temp_collision_sealed_temp_file}" "existing temp")
run_cli_no_stdout(seal-file --in "${plain_file}" --out "${temp_collision_sealed_file}" --key-file "${key_file}" --aad-text record:v1)
if(NOT EXISTS "${temp_collision_sealed_file}")
  message(FATAL_ERROR "installed CLI seal-file did not create output when legacy temporary output existed")
endif()
file(READ "${temp_collision_sealed_temp_file}" temp_collision_text)
if(NOT temp_collision_text STREQUAL "existing temp")
  message(FATAL_ERROR "installed CLI seal-file changed existing temporary output")
endif()
file(REMOVE "${temp_collision_sealed_temp_file}")

file(WRITE "${temp_collision_opened_temp_file}" "existing temp")
run_cli_no_stdout(open-file --in "${sealed_file}" --out "${temp_collision_opened_file}" --key-file "${key_file}" --aad-text record:v1)
file(READ "${temp_collision_opened_file}" temp_collision_opened_text)
if(NOT temp_collision_opened_text STREQUAL "installed CLI plaintext\n")
  message(FATAL_ERROR "installed CLI open-file did not recover plaintext when legacy temporary output existed. got=[${temp_collision_opened_text}]")
endif()
file(READ "${temp_collision_opened_temp_file}" temp_collision_text)
if(NOT temp_collision_text STREQUAL "existing temp")
  message(FATAL_ERROR "installed CLI open-file changed existing temporary output")
endif()
file(REMOVE "${temp_collision_opened_temp_file}")

run_cli_pipe("${plain_file}" "${pipe_sealed_file}" seal-file --in - --out - --key-file "${key_file}" --aad-text record:v1)
run_cli_pipe("${pipe_sealed_file}" "${pipe_opened_file}" open-file --in - --out - --key-file "${key_file}" --aad-text record:v1)
file(READ "${pipe_opened_file}" pipe_opened_text)
if(NOT pipe_opened_text STREQUAL "installed CLI plaintext\n")
  message(FATAL_ERROR "installed CLI piped open did not recover plaintext. got=[${pipe_opened_text}]")
endif()

run_cli_no_stdout(seal-file-password --out "${password_sealed_file}" --password-file "${password_file}" --aad-text record:v1 --in "${plain_file}")
file(READ "${password_sealed_file}" password_sealed_hex HEX)
if(NOT password_sealed_hex MATCHES "^534b503101010100[0-9a-f]+$")
  message(FATAL_ERROR "installed CLI seal-file-password did not write a binary SKP1 file")
endif()
run_cli_no_stdout(open-file-password --password-file "${password_file}" --out "${password_opened_file}" --aad-text record:v1 --in "${password_sealed_file}")
file(READ "${password_opened_file}" password_opened_text)
if(NOT password_opened_text STREQUAL "installed CLI plaintext\n")
  message(FATAL_ERROR "installed CLI open-file-password did not recover plaintext. got=[${password_opened_text}]")
endif()
run_cli_failure("File authentication failed\n" open-file-password --in "${password_sealed_file}" --out "${password_wrong_opened_file}" --password-file "${wrong_password_file}" --aad-text record:v1)

run_cli_pipe("${plain_file}" "${password_pipe_sealed_file}" seal-file-password --in - --out - --password-file "${password_file}" --aad-text record:v1)
run_cli_pipe("${password_pipe_sealed_file}" "${password_pipe_opened_file}" open-file-password --in - --out - --password-file "${password_file}" --aad-text record:v1)
file(READ "${password_pipe_opened_file}" password_pipe_opened_text)
if(NOT password_pipe_opened_text STREQUAL "installed CLI plaintext\n")
  message(FATAL_ERROR "installed CLI piped password open did not recover plaintext. got=[${password_pipe_opened_text}]")
endif()

run_cli_no_stdout(encrypt --in "${plain_file}" --out "${packet_file}" --key-file "${key_file}" --aad-text record:v1)
run_cli_no_stdout(decrypt --packet-file "${packet_file}" --out "${packet_opened_file}" --key-file "${key_file}" --aad-text record:v1)
file(READ "${packet_opened_file}" packet_opened_text)
if(NOT packet_opened_text STREQUAL "installed CLI plaintext\n")
  message(FATAL_ERROR "installed CLI decrypt --out did not recover plaintext. got=[${packet_opened_text}]")
endif()

run_cli_no_stdout(seal-file --in "${plain_file}" --out "${unwrapped_key_sealed_file}" --key-file "${unwrapped_key_file}")
run_cli_no_stdout(open-file --in "${unwrapped_key_sealed_file}" --out "${unwrapped_key_opened_file}" --key-file "${unwrapped_key_file}")
file(READ "${unwrapped_key_opened_file}" unwrapped_key_opened_text)
if(NOT unwrapped_key_opened_text STREQUAL "installed CLI plaintext\n")
  message(FATAL_ERROR "installed CLI unwrapped key file did not recover plaintext. got=[${unwrapped_key_opened_text}]")
endif()

run_cli_failure("conflicting key options\n" seal-file --in "${plain_file}" --out "${conflicting_key_file}" --key-file "${key_file}" --key-hex "${generated_key_text}")
run_cli_failure("AEAD authentication failed\n" decrypt --packet-file "${packet_file}" --out "${SECUREKIT_CLI_WORK_DIR}/securekit-installed-cli-wrong-aad.txt" --key-file "${key_file}" --aad-text record:v2)
