if(NOT DEFINED SECUREKIT_WORKFLOW_FILE)
  set(SECUREKIT_WORKFLOW_FILE "${CMAKE_CURRENT_LIST_DIR}/../../.github/workflows/securekit-ci.yml")
endif()

if(NOT DEFINED SECUREKIT_CODEQL_WORKFLOW_FILE)
  set(SECUREKIT_CODEQL_WORKFLOW_FILE "${CMAKE_CURRENT_LIST_DIR}/../../.github/workflows/codeql.yml")
endif()

if(NOT EXISTS "${SECUREKIT_WORKFLOW_FILE}")
  message(FATAL_ERROR "Workflow file not found: ${SECUREKIT_WORKFLOW_FILE}")
endif()

if(NOT EXISTS "${SECUREKIT_CODEQL_WORKFLOW_FILE}")
  message(FATAL_ERROR "CodeQL workflow file not found: ${SECUREKIT_CODEQL_WORKFLOW_FILE}")
endif()

file(READ "${SECUREKIT_WORKFLOW_FILE}" _securekit_workflow)
file(READ "${SECUREKIT_CODEQL_WORKFLOW_FILE}" _securekit_codeql_workflow)
string(REPLACE "\r\n" "\n" _securekit_workflow "${_securekit_workflow}")
string(REPLACE "\r" "\n" _securekit_workflow "${_securekit_workflow}")
string(REPLACE "\r\n" "\n" _securekit_codeql_workflow "${_securekit_codeql_workflow}")
string(REPLACE "\r" "\n" _securekit_codeql_workflow "${_securekit_codeql_workflow}")

function(_securekit_require_workflow_text description needle)
  string(FIND "${_securekit_workflow}" "${needle}" _securekit_found_at)
  if(_securekit_found_at EQUAL -1)
    message(FATAL_ERROR "Workflow missing ${description}: ${needle}")
  endif()
endfunction()

function(_securekit_require_codeql_text description needle)
  string(FIND "${_securekit_codeql_workflow}" "${needle}" _securekit_found_at)
  if(_securekit_found_at EQUAL -1)
    message(FATAL_ERROR "CodeQL workflow missing ${description}: ${needle}")
  endif()
endfunction()

function(_securekit_require_codeql_regex description pattern)
  string(REGEX MATCH "${pattern}" _securekit_match "${_securekit_codeql_workflow}")
  if(_securekit_match STREQUAL "")
    message(FATAL_ERROR "CodeQL workflow missing ${description}: ${pattern}")
  endif()
endfunction()

_securekit_require_workflow_text("tag trigger" "tags:")
_securekit_require_workflow_text("v tag pattern" "- 'v*'")
_securekit_require_workflow_text("default read-only token permission" "permissions:\n  contents: read")
_securekit_require_workflow_text("release job" "release:")
_securekit_require_workflow_text("release dependency on build matrix" "needs: [build, install-only, linux-static, windows-shared, linux-sanitizers, macos-package]")
_securekit_require_workflow_text("release tag guard" "startsWith(github.ref, 'refs/tags/v')")
_securekit_require_workflow_text("release write token permission" "permissions:\n      contents: write")
_securekit_require_workflow_text("release OIDC token permission" "id-token: write")
_securekit_require_workflow_text("release attestation permission" "attestations: write")
_securekit_require_workflow_text("current checkout action" "uses: actions/checkout@v7")
_securekit_require_workflow_text("current cache action" "uses: actions/cache@v5")
_securekit_require_workflow_text("current upload artifact action" "uses: actions/upload-artifact@v7")
_securekit_require_workflow_text("warnings as errors CI option" "-DSECUREKIT_WARNINGS_AS_ERRORS=ON")
_securekit_require_workflow_text("Linux sanitizer job" "linux-sanitizers:")
_securekit_require_workflow_text("Linux sanitizer name" "ubuntu-latest clang Debug sanitizers")
_securekit_require_workflow_text("address sanitizer flag" "-fsanitize=address,undefined")
_securekit_require_workflow_text("sanitizer check target" "cmake --build build --config Debug --target check")
_securekit_require_workflow_text("macOS package job" "macos-package:")
_securekit_require_workflow_text("macOS job name" "macos-latest appleclang Release package")
_securekit_require_workflow_text("macOS OpenSSL dependency" "brew install ninja openssl@3")
_securekit_require_workflow_text("macOS OpenSSL root" "-DOPENSSL_ROOT_DIR=\"\$(brew --prefix openssl@3)\"")
_securekit_require_workflow_text("macOS package target" "cmake --build build --config Release --target package-check")
_securekit_require_workflow_text("matrix package artifact" "securekit-\${{ matrix.os }}-\${{ matrix.compiler }}-\${{ matrix.build_type }}-packages")
_securekit_require_workflow_text("install-only package artifact" "securekit-ubuntu-gcc-release-install-only-packages")
_securekit_require_workflow_text("Linux static package artifact" "securekit-ubuntu-gcc-release-static-packages")
_securekit_require_workflow_text("Windows shared package artifact" "securekit-windows-msvc-release-shared-packages")
_securekit_require_workflow_text("macOS package artifact" "securekit-macos-clang-release-packages")
_securekit_require_workflow_text("release artifact download" "uses: actions/download-artifact@v8")
_securekit_require_workflow_text("package artifact ZIP upload filter" "build/package-check/artifacts/*.zip")
_securekit_require_workflow_text("package artifact TGZ upload filter" "build/package-check/artifacts/*.tar.gz")
_securekit_require_workflow_text("release tag version extraction" "tag_version=\"\${GITHUB_REF_NAME#v}\"")
_securekit_require_workflow_text("release asset ZIP glob" "release-artifacts/*/securekit-\"\$tag_version\"-*.zip")
_securekit_require_workflow_text("release asset TGZ glob" "release-artifacts/*/securekit-\"\$tag_version\"-*.tar.gz")
_securekit_require_workflow_text("release artifact version guard" "Release artifact version does not match tag")
_securekit_require_workflow_text("release SemVer tag guard" "Release tag is not SemVer")
_securekit_require_workflow_text("release binary artifact prefix" "dist/\${artifact_name}-\${base}")
_securekit_require_workflow_text("release source artifact de-duplication" "copied_source")
_securekit_require_workflow_text("release source ZIP requirement" "expected_source_zip=\"securekit-\${tag_version}-source.zip\"")
_securekit_require_workflow_text("release source TGZ requirement" "expected_source_tgz=\"securekit-\${tag_version}-source.tar.gz\"")
_securekit_require_workflow_text("release expected binary artifact list" "expected_binary_artifacts=(")
_securekit_require_workflow_text("release expected GCC Release binary artifact" "\"securekit-ubuntu-latest-gcc-Release-packages\"")
_securekit_require_workflow_text("release expected Clang Release binary artifact" "\"securekit-ubuntu-latest-clang-Release-packages\"")
_securekit_require_workflow_text("release expected GCC Debug binary artifact" "\"securekit-ubuntu-latest-gcc-Debug-packages\"")
_securekit_require_workflow_text("release expected MSVC Release binary artifact" "\"securekit-windows-latest-msvc-Release-packages\"")
_securekit_require_workflow_text("release expected install-only binary artifact" "\"securekit-ubuntu-gcc-release-install-only-packages\"")
_securekit_require_workflow_text("release expected static binary artifact" "\"securekit-ubuntu-gcc-release-static-packages\"")
_securekit_require_workflow_text("release expected shared binary artifact" "\"securekit-windows-msvc-release-shared-packages\"")
_securekit_require_workflow_text("release expected macOS binary artifact" "\"securekit-macos-clang-release-packages\"")
_securekit_require_workflow_text("release expected binary suffix list" "expected_binary_suffixes=(\".zip\" \".tar.gz\")")
_securekit_require_workflow_text("release source ZIP guard" "No source ZIP package artifact found")
_securekit_require_workflow_text("release source TGZ guard" "No source TGZ package artifact found")
_securekit_require_workflow_text("release binary artifact guard" "No binary \$expected_binary_suffix package artifact found for")
_securekit_require_workflow_text("release SBOM file name" "sbom_name=\"securekit-\${tag_version}-release.spdx.json\"")
_securekit_require_workflow_text("release SBOM generation step" "- name: Generate release SBOM")
_securekit_require_workflow_text("release SBOM SPDX version" "spdxVersion")
_securekit_require_workflow_text("release checksum generation" "sha256sum")
_securekit_require_workflow_text("release checksum file" "SHA256SUMS.txt")
_securekit_require_workflow_text("release artifact attestation action" "uses: actions/attest-build-provenance@v3")
_securekit_require_workflow_text("release artifact attestation subject" "subject-path: dist/*")
_securekit_require_workflow_text("release artifact download step" "- name: Download package artifacts")
_securekit_require_workflow_text("release edit title only" "gh release edit \"$tag\" --title \"$title\"")
_securekit_require_workflow_text("release create generated notes" "gh release create \"$tag\" --verify-tag --title \"$title\" --generate-notes")
_securekit_require_workflow_text("release creation" "gh release create")
_securekit_require_workflow_text("release asset upload" "gh release upload")

_securekit_require_codeql_text("workflow name" "name: \"CodeQL\"")
_securekit_require_codeql_regex("main push trigger" "push:[\r\n]+    branches: \\[ \"main\" \\]")
_securekit_require_codeql_regex("main pull request trigger" "pull_request:[\r\n]+    branches: \\[ \"main\" \\]")
_securekit_require_codeql_regex("scheduled analysis" "schedule:[\r\n]+    - cron:")
_securekit_require_codeql_text("current checkout action" "uses: actions/checkout@v7")
_securekit_require_codeql_text("current CodeQL init action" "uses: github/codeql-action/init@v4")
_securekit_require_codeql_text("manual CodeQL build mode" "build-mode: manual")
_securekit_require_codeql_text("manual CMake configure" "cmake -S . -B build-codeql")
_securekit_require_codeql_text("manual CMake build" "cmake --build build-codeql --config Release")
_securekit_require_codeql_text("current CodeQL analyze action" "uses: github/codeql-action/analyze@v4")
